name: Daniel Husar
markdown: redcarpet
pygments: true
permalink: /:title

#RSS settings
url: www.danielhusar.sk
author: Daniel Husar
rss_post_limit: 10

#files to exclude, array
exclude:
  - README.md
  - LICENSE

#Categories
category_dir: tag
category_title_prefix: ''
