name: Daniel Husar
markdown: redcarpet
pygments: true
permalink: /:title
timezone: Europe/Dublin
paginate: 10
paginate_subpath: strana
paginate_path: "/strana/:num"

#RSS settings
url: http://www.danielhusar.sk
author: Daniel Husar
rss_post_limit: 10

#Files to exclude, array
exclude:
  - README.md
  - LICENSE
  - gulpfile.js
  - package.json
  - css.mustache
  - node_modules

#Categories
category_dir: tag
category_title_prefix: ''

#Production
prod: false
